### PR TITLE
Implement concat for OnnxTensor

### LINKED ISSUE #19: Not implementederror
Traceback (most recent call last):
  File "onnx2keras.py", line 642, in <module>
    Fire(main)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "onnx2keras.py", line 633, in main
    model = onnx2keras(onnx.load(infile))
  File "onnx2keras.py", line 621, in onnx2keras
    output_tensors = ops.make_op(node.op_type, inputs, attrs)
  File "onnx2keras.py", line 18, in make_op
    return getattr(self, 'op_' + op_type.lower())(*inputs, **attrs)
  File "onnx2keras.py", line 213, in op_concat
    raise NotImplementedError
NotImplementedError

### PR DESCRIPTION
**Pull request by xsacha**
Fixes #19

### CODE REVIEW

**Comment by hakanardo** [comment]
Thanx! Please consider adding a test in test_onnx2keras.py aswell.

**Comment by xsacha** [comment]
I tried to create a test for it but wasn't sure how to get the OnnxTensor type through.

**Comment by hakanardo** [comment]
Concating OnnxTensors will not always resut in an InterleavedImageBatch. Do you have some (preferable minimal) example model you could share that triggers the issue? (That's what we'll need for the test anyway).

**Comment by xsacha** [comment]
I'm not entirely sure how it produces that OnnxTensor input. Anything that produces that would be the test.

The line in PyTorch looks like:
```Python
classifications = torch.cat([self.ClassHead[i](feature).permute(0,2,3,1).reshape(batch, -1, 2) for i, feature in enumerate(features)],dim=1)
```
Is it due to the reshape maybe?

**Pull request closed without merging**
